[build]
  command = "npx prisma generate && npx next build"
  publish = ".next"

[functions]
  external_node_modules = ["@prisma/client", "prisma"]
  included_files = ["node_modules/.prisma/client/**", "prisma/**"]
